apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-app.configMapName" . | quote }}
data:
  DB_HOST: {{ include "user-app.dbhost" . | quote }}
  DB_PORT: {{ .Values.postgresql.primary.service.port | quote }}
{{/*  DB_HOST: "my-postgres"*/}}
{{/*  DB_PORT: "5432"*/}}
  DB_NAME: {{.Values.configMap.db.name|quote}}
  DB_DRIVER: {{ .Values.configMap.db.driver | quote }}
{{/*  APP_PORT: "8000"*/}}