# Default values for user-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: lexxyar/otus-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.5"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80
  containerPort: 8000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  pathType: Prefix
  className: nginx
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix

postgresql:
  nameOverride: "my-postgresql"

  auth:
    postgresPassword: "postgres-password"
    username: "user"
    database: "userdb"
    existingSecret: user-db-secret
    secretKeys:
      userPasswordKey: DB_PASSWORD

  primary:
    service:
      type: ClusterIP
      port: 5432
    persistence:
      enabled: true
      size: 1Gi

  architecture: "standalone"

configMap:
  db:
    driver: "postgresql"
    name: "userdb"
#  DB_HOST: "my-postgres"
#  DB_PORT: "5432"
#  DB_NAME: "userdb"
#  app:
#    port: "8000"
#    APP_PORT: "8000"


# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 2
  periodSeconds: 5
