openapi: 3.1.0
info:
  title: Сервис авторизации
  description: Сервис авторизации и управления пользователями
  version: 1.0.0
servers:
  - url: 'https://newsubway.shop/api/v1'
tags:
  - name: Auth
    description: Auth actions
  - name: User
    description: User actions
paths:
  # Auth
  /auth/login:
    post:
      tags:
        - Auth
      summary: Авторизация
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        422:
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InvalidCredentials'

  /auth/logout:
    post:
      tags:
        - Auth
      summary: Выход из системы
      operationId: logout
      security:
        - bearerAuth: [ ]
      responses:
        204:
          description: Logout successfully
        401:
          $ref: '#/components/responses/Unauthorized'

  /auth/register:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Register"
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        422:
          $ref: '#/components/responses/InvalidCredentials'

  /auth/me:
    get:
      tags:
        - Auth
      summary: Профиль пользователя
      operationId: getUserProfile
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: User credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        401:
          $ref: '#/components/responses/Unauthorized'
    put:
      tags:
        - Auth
      summary: Обновление профиля пользователя
      operationId: putUserProfile
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Profile"
      responses:
        200:
          description: User credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        401:
          $ref: '#/components/responses/Unauthorized'
        422:
          $ref: '#/components/responses/InvalidCredentials'
    delete:
      tags:
        - Auth
      summary: Удаление профиля пользователя
      operationId: deleteUserProfile
      security:
        - bearerAuth: [ ]
      responses:
        204:
          description: Профиль удален
        401:
          $ref: '#/components/responses/Unauthorized'


components:
  securitySchemes:
    bearerAuth:
      $ref: "../schemas/security.yaml#/bearerAuth"
  responses:
    Unauthorized:
      $ref: "../schemas/common.yaml#/Unauthorized"
    NotFound:
      $ref: "../schemas/common.yaml#/NotFound"
    InvalidCredentials:
      $ref: "../schemas/common.yaml#/InvalidCredentials"
  schemas:
    Login:
      $ref: "../schemas/auth.yaml#/Login"
    Register:
      $ref: "../schemas/auth.yaml#/Register"
    Profile:
      $ref: "../schemas/user.yaml#/Profile"
    Token:
      $ref: "../schemas/auth.yaml#/Token"

