openapi: 3.1.0
info:
  title: Сервис заказов и покупательской корзины
  description: Сервис управления корзиной покупок и оформленных заказов
  version: 1.0.0
servers:
  - url: 'https://newsubway.shop/api/v1'
tags:
  - name: Cart
  - name: Order
paths:
  #  Cart
  /cart:
    get:
      tags:
        - Cart
      summary: Получить корзину покупок посетителя
      operationId: getCart
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    post:
      tags:
        - Cart
      summary: Добавить/изменить количество товар в корзину посетителя
      operationId: changeCart
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CartItem"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartItem"
  /cart/{productId}:
    delete:
      tags:
        - Cart
      summary: Удалить товар из корзины посетителя
      operationId: deleteFromCart
      parameters:
        - $ref: "#/components/parameters/ProductIdParam"
      responses:
        204:
          description: Deleted

  #  Order
  /orders:
    get:
      tags:
        - Order
      summary: Выбрать заказы
      operationId: getOrderList
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        401:
          $ref: '#/components/responses/Unauthorized'
    post:
      tags:
        - Order
      summary: Создать заказ
      operationId: createOrder
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CartItem"
      responses:
        201:
          description: Created new order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderState"
        401:
          $ref: '#/components/responses/Unauthorized'

  /orders/byId/{orderId}:
    get:
      tags:
        - Order
      summary: Выбрать заказ по идентификатору
      operationId: getOrderById
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: "#/components/parameters/OrderIdParam"
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
    put:
      tags:
        - Order
      summary: Обновить заказ
      operationId: updateOrder
      parameters:
        - $ref: "#/components/parameters/OrderIdParam"
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        204:
          description: success
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - Order
      summary: Удалить заказ
      operationId: deleteOrder
      parameters:
        - $ref: "#/components/parameters/OrderIdParam"
      security:
        - bearerAuth: [ ]
      responses:
        204:
          description: success
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: "#/components/responses/NotFound"
  /orders/byId/{orderId}/{status}:
    put:
      tags:
        - Order
      summary: Обновить статус заказ
      operationId: updateOrderStatus
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: "#/components/parameters/OrderIdParam"
        - $ref: "#/components/parameters/OrderStatusParam"
      responses:
        204:
          description: success
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: "#/components/responses/NotFound"
  /orders/byShop/{shopId}:
    get:
      tags:
        - Order
      summary: Выбрать заказы магазина
      operationId: getOrderListByShop
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: "#/components/parameters/ShopIdParam"
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: "#/components/responses/NotFound"

  /orders/byStatus/{status}:
    get:
      tags:
        - Order
      summary: Выбрать заказы по статусу
      operationId: getOrderListByStatus
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: "#/components/parameters/OrderStatusParam"
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: "#/components/responses/NotFound"

components:
  securitySchemes:
    bearerAuth:
      $ref: "../schemas/security.yaml#/bearerAuth"
  responses:
    Unauthorized:
      $ref: "../schemas/common.yaml#/Unauthorized"
    NotFound:
      $ref: "../schemas/common.yaml#/NotFound"
  parameters:
    ProductIdParam:
      $ref: "../schemas/common.yaml#/ProductIdParam"
    ShopIdParam:
      $ref: "../schemas/common.yaml#/ShopIdParam"
    OrderIdParam:
      $ref: "../schemas/common.yaml#/OrderIdParam"
    OrderStatusParam:
      $ref: "../schemas/common.yaml#/OrderStatusParam"
  schemas:
    CartItem:
      $ref: "../schemas/cart.yaml#/CartItem"
    Cart:
      $ref: "../schemas/cart.yaml#/Cart"
    Order:
      $ref: "../schemas/order.yaml#/Order"
    OrderState:
      $ref: "../schemas/order.yaml#/OrderState"
