apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-app.serviceName" . }}
  labels:
    app: {{ include "user-app.appName" . | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.service.containerPort}}
      protocol: TCP
  selector:
    app: {{ include "user-app.appName" . | quote }}
